apiVersion: v1
kind: Secret
metadata:
  name: mysql-auth
type: Opaque
data:
   MYSQL_ROOT_PASSWORD: ZHJhZ29ud3d3d3d3
   MYSQL_DATABASE: Y2hhcnRtaXJ1
   MYSQL_USER: Y2hhcnRtaXJ1
   MYSQL_PASSWORD: Q2hAcnRtaXJ1MDMxMw==