apiVersion: v1
kind: Pod
metadata:
  name: chartmiru-batch
spec:
  volumes:
  # mount db for dev
    - name: mysql-local-volume
      hostPath:
        path: ~/chartmiru/batch.chartmiru/Database/data
        type: DirectoryOrCreate
  # mount mysql.cnf
    - name: mysql-config-volume
      configMap:
        name: mysql-config
        items:
        - key: my.cnf
          path: my_test.cnf


  containers:
    - image: asia.gcr.io/chartmiru/chartmiru_batch
      name: batch
      imagePullPolicy: IfNotPresent
    - image: asia.gcr.io/chartmiru/mysql
      name: db
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-local-volume
          mountPath: /var/lib/mysql
        - name: mysql-config-volume
          mountPath: /usr/local/etc