apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: chartmiru-batch
spec:
  replicas: 1
  selector:
    # このセレクタでPodを選択する
    matchLabels:
      # deploymentで指定したラベル
      batch: chartmiru
  template:
    metadata:
      labels:
        # セレクタと同じ値
        batch: chartmiru
    spec:
      containers:
        - image: asia.gcr.io/chartmiru/chartmiru_batch
          name: batch
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: code-local-volume
              mountPath: /root
        - image: asia.gcr.io/chartmiru/mysql
          name: db
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: mysql-auth
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-local-volume
              mountPath: /var/lib/mysql
            - name: mysql-config-volume
              mountPath: /usr/local/etc
      volumes:
      # mount db for dev
        - name: mysql-local-volume
          hostPath:
      #must be full pass
            path: /Users/yuichirotakarada/chartmiru/ChartMiru-Batch/Database/data
            type: DirectoryOrCreate
      # mount mysql.cnf
        - name: mysql-config-volume
          configMap:
            name: mysql-config
            items:
            - key: my.cnf
              path: my.cnf
      # mount code for dev
        - name: code-local-volume
          hostPath:
            path: /Users/yuichirotakarada/chartmiru/ChartMiru-Batch/
            type: Directory